### PR TITLE
First working version of wblib 

### PR DESCRIPTION
**Pull request by sortega87**
Including changes in the repository for:

- Having a first working version of wblib that can produce a minimal presentation for quarto.
- Refactor the plots to adapt them to what is expected from the library. 
- Cleaning old files that were not being used.

Please make sure to review the plot modules. Thanks!

### CODE REVIEW

**Comment by sortega87** [comment]
I have further included changes to icwv.py pointed out by Dyvia, added the full briefing template as a reference for later developments, and modified the README.md file to clarify how to work with wblib. :)

**Comment by lkluft** [comment]
Congratulations on the first working version! 🎉 

From a quick look at the branch, there seem to be some redundant commits in there. Maybe a rebase would clean up the history a bit. Also, there are a lot of static binaries (e.g. PNG) in there. Is this on purpose?

**Comment by sortega87** [comment]
> Congratulations on the first working version! 🎉
> 
> From a quick look at the branch, there seem to be some redundant commits in there. Maybe a rebase would clean up the history a bit. Also, there are a lot of static binaries (e.g. PNG) in there. Is this on purpose?

Thanks Lukas!

Yes, definitively some redundant commits. As we are still in a early stage of the repo, I was thinking we could squash all commits on merging to the main branch after the review. Yet, I'm not sure how to clean the history with rebase. Is there something you have in mind we could do?

**Review by dspraturi — COMMENTED** [review]
I mostly checked the changes to icwv.py, which during discussions with @sortega87 make sense to me. It would be great if we can finalize the decision on where to store the .png files.

**Comment by sortega87** [comment]
> I mostly checked the changes to icwv.py, which during discussions with @sortega87 make sense to me. It would be great if we can finalize the decision on where to store the .png files.

Thanks Divya!

Regarding the PNG file, I would suggest to store them in the repository for the moment, then discussing this point in our next group meeting, and then opening an issue to work in this point if we decide on storing them somewhere else. Yet, I might be wrong. Perhaps is better to do something else from the beginning?

**Comment by lkluft** [comment]
> [...] Yet, I'm not sure how to clean the history with rebase. Is there something you have in mind we could do?

My idea would have been that a simple rebase on the current main branch should get rid off the duplicate commits that are already included.

> Regarding the PNG file, [...] Perhaps is better to do something else from the beginning?

One downside of this is, that the repo size would already increase significantly. In theory, it would be cool if all images are created on-the-fly by a CI. One could then decided to either
1. Re-build **all** images **everytime** (this needs trust in the data sources)
2. or store the `.jupytercache` (which is populated during the CI build) in the published `gh-pages` branch only

**Comment by sortega87** [comment]
Thanks Lukas! Yes, perhaps we should use rebasing instead of merge in the future. Regarding the files, rebuilding every time would not be an option for us, as we want to make sure that the information used to make each report does not change with time.

**Comment by sortega87** [comment]
Hi @dspraturi, now merging the branch as discussed.

**Pull request merged**
