### PR TITLE
Adding the plots of surface wind convergence to the weather briefing

### PR DESCRIPTION
**Pull request by dspraturi**
This closes the issue #169 and adds the plots of forecasted convergence to the briefing. 

Here is a sample plot of convergence. It looks a bit noisy (to be expected) but there is dominant convergence in the ITCZ. I have mostly repurposed the scripts that I typically use to compute convergence in nextgems data. 
test_sfc_conv

I also tested with generating the briefing - it works without any issues. :)

### CODE REVIEW

**Review by HF7weatherman — CHANGES_REQUESTED** [review]
Hi @dspraturi! Thank you very much for these great plots, I think they would be really helpful for flight planning :) @sortega87 and me just had a quick discussion on this topic and we both agreed on putting these figures into a separate section `Supporting figures` in the end of the briefing, as they are really helpful for flight planning, but too lenghty for the briefing itself. @sortega87 will implement this change.

**Comment by sortega87** [comment]
Thanks @dspraturi! Looks very nice. I will make some changes in the quarto template of this branch to include it as a supporting figure of the presentation. We thought it is good to include these and other figures here first.

Is it possible to also compute the vorticity in the healpix grid? That would be a great complement for the briefing.

**Comment by sortega87** [comment]
@HF7weatherman I have now included the support section in the quarto template

**Comment by sortega87** [comment]
I think now its ready to merge.

**Review by HF7weatherman — CHANGES_REQUESTED** [review]
Hey @sortega87! I just realized this branch does not have yesterday's hotfix included, which changed one lead time from `+087h` back to `+084h`. Could you please merge `main` back to the present branch before merging it back to `main`. This should fix most of it, but I think then there's still a change from `+087h` back to `+084h` necessary for the new figures in `template.qmd`.

**Comment by HF7weatherman** [comment]
@dspraturi In case you have an easy way to calculate surface vorticity and would like to implement it: Please have a look at #191 👍🏻

**Review by HF7weatherman — APPROVED** [review]

**Comment by HF7weatherman** [comment]
Looks fine, can be merged 👍🏻

**Comment by HF7weatherman** [comment]
@sortega87 When trying to generate the briefing, I get the following error message when the code tries to generate the new figures:

```
OMP: Error #15: Initializing libomp.dylib, but found libomp.dylib already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://openmp.llvm.org/
./wbcli.sh: line 4: 17487 Abort trap: 6           python3 src/wblib/main.py "$@"
/opt/homebrew/Caskroom/miniforge/base/envs/wblib/lib/python3.12/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 2 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

Surprisingly, Python really crashes and not only throws this error. I think it has something to do with your speed-up changes, which may have not been implemented for the new convergence plots.

We should fix this tomorrow. For now, I will create a branch `temporary_main` from the last commit on `main` before the merge, which I`ll use to generate the weather briefings 👍🏻

**Comment by sortega87** [comment]
Hi @HF7weatherman! Sorry for this, and thanks for letting me know. Let's take a look today, perhaps we should revert the changes regarding preloading the dask array. I tried generating all the figures in my computer and it is working without showing the warning or crashing. I wonder if it is due to differences in my environment.

**Pull request merged**
