### PR TITLE
Refactor figures

### PR DESCRIPTION
**Pull request by sortega87**
This solves #44. It refactor the internal and external functions, and also makes changes that have been recently discussed.

The main refactoring of the external functions are the following:
- Decoupled ecmwf.py from hifs.py. In tests made not passing "base_time" to the ECMWF API return the latest available. This should be preferable. 
- Now all external figures receive current time and location information.

The main refactoring of the internal functions are the following:
- Added class HifsForecasts that manages access to IFS forecast data. It also manages getting instantaneous values from accumulated ones.
- Added module briefing_info.py with definition of valid date and a method to format axes for all internal figures.
- Refactored internal figure functions to use the new classes and methods.
- Refactored the interface of the internal figures.

The main changes in the internal functions are the following:
- Adjusted domain of plots making it common for all.
- Adjusted colormap of plot with lattes comments.

### CODE REVIEW

**Comment by sortega87** [comment]
@HF7weatherman I converted it to draft to work on the refactoring of internal figures as well

**Comment by sortega87** [comment]
> Hi @sortega87! Thanks for working on the refactoring! :) Please let me know when you think you're done, then I'll start with the review.

Thanks @HF7weatherman! Now it is ready for review. Note the changes in the description of the PR. Let me know what you think.

**Review by HF7weatherman — APPROVED** [review]
Hi Sebastian, thank you very much for this work, the new interface is pretty amazing! Also the figures look really great now, especially the ICWV one. I'll merge back now as it's good to have it in main asap. Probably these changes will cause merge conflicts with the MR for the sattracks, but I'll figure them out.

**Comment by sortega87** [comment]
> Hi Sebastian, thank you very much for this work, the new interface is pretty amazing! Also the figures look really great now, especially the ICWV one. I'll merge back now as it's good to have it in main asap. Probably these changes will cause merge conflicts with the MR for the sattracks, but I'll figure them out.

Hi @HF7weatherman. Thanks for the review! Sound good, let me know if can help with the sattracks merge request. :)

**Pull request merged**
