### PR TITLE
Cuttinh the hovmoller image

### PR DESCRIPTION
**Pull request by sortega87**

### CODE REVIEW

**Review by dspraturi — COMMENTED** [review]
Could you also provide an example of what the cropped image would look like?

**Comment by sortega87** [comment]
> Could you also provide an example of what the cropped image would look like?
@dspraturi, yes, this is an example of the image. Let me know what you think :)
image

**Comment by HF7weatherman** [comment]
Looks fine for me! :)

**Comment by dspraturi** [comment]
Looks good to me too. 🙂

**Pull request merged**
